### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found. 

### ISSUE THREAD

**Issue by namename-123** [Vinyzu/Botright#96] opened 2024-04-27 15:32 UTC
Hello I keep getting the following error when running botright:
`OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.`

My code is very simple:

`import asyncio

import botright

async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    page = await browser.new_page()

    # Continue by using the Page
    await page.goto("https://google.com")

    await botright_client.close()

if __name__ == "__main__":
    asyncio.run(main())`

**Comment by Vinyzu** [comment] 2024-04-29 12:42
Closing as Duplicate of [#95](https://github.com/Vinyzu/Botright/issues/95)

**Closed by Vinyzu** 2024-04-29 12:42 UTC
Labels: bug, help wanted
