### ISSUE TITLE
[BUG] RuntimeError: Event loop is closed, ValueError: I/O operation on closed pipe

### ISSUE THREAD

**Issue by krsamue101** [Vinyzu/Botright#21] opened 2023-11-04 07:10 UTC
Hello! 
Thank you for sharing this!

I'm tried sample code on docs. But getting 
```
2023-11-04 16:01:45,483 ERROR Task exception was never retrieved
future: <Task finished name='Task-68' coro=<Response.finished.<locals>.on_finished() done, defined at C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\_impl\_network.py:544> exception=Error('Target closed')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\_impl\_network.py", line 546, in on_finished
    raise Error("Target closed")
playwright._impl._api_types.Error: Target closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001CF603689A0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001CF6033F240>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function StreamWriter.__del__ at 0x000001CF60323EC0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 395, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 343, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 761, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I'm using Windows 11 and 3.11.6

Thank you

**Comment by krsamue101** [comment] 2023-11-04 07:11
Also solve_hcaptcha() returns None even if the captcha solved. It works with page.evaluate('hcaptcha.getResponse()') but I think it should be fixed

**Comment by Vinyzu** [comment] 2023-11-04 08:19
Sure, ill have to fix many parts of hcaptcha mext update anyway.
The error you described above happens when you either Exit Python Forcefully (Many Ctrl+C for example) or close a browser controlled by Botright manually. This is not an issue of botright as it is expected behavior of playwright.

**Comment by krsamue101** [comment] 2023-11-04 11:41
https://github.com/Vinyzu/Botright/assets/105032235/7777c564-4c85-4296-8485-7e1a8681f158

It happens without closing a browser or close forcefully

**Comment by Vinyzu** [comment] 2024-01-17 20:08
Fixed in a previous Update, due to using [hcaptcha-challenger](https://github.com/QIN2DIM/hcaptcha-challenger)´s playwright implementation.

**Closed by Vinyzu** 2024-01-17 20:08 UTC
Labels: bug, help wanted
