### ISSUE TITLE
[BUG] HCaptcha on discord not loaded

### ISSUE THREAD

**Issue by krsamue101** [Vinyzu/Botright#23] opened 2023-11-04 17:34 UTC
![image](https://github.com/Vinyzu/Botright/assets/105032235/9346abcd-27e8-4258-b92d-ceccbbd65dcc)
Tried changing ip but not worked. But hcaptcha loads on other browsers( chrome, edge, brave.. etc) loaded captcha successfully
```
async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    page = await browser.new_page()
    await page.goto("https://discord.com") # load|domcontentloaded|networkidle|commit
```

**Comment by Vinyzu** [comment] 2023-11-09 10:17
Confirmed, sometimes takes 1-2 reloads for it to load. Will investigate

**Comment by TheRealPerson98** [comment] 2023-11-16 01:27
Also having this problem.

**Comment by lxntagram** [comment] 2024-01-18 09:48
When it will be fixed? It seems argument issue

**Comment by Vinyzu** [comment] 2024-01-19 06:35
Will work on it soon

**Closed** 2024-01-24 18:24 UTC
Labels: bug, help wanted

**Comment by lxntagram** [comment] 2024-02-10 03:42
Now it loads hcaptcha but it refresh captcha itself and closes captcha

https://github.com/Vinyzu/Botright/assets/133577870/54426aaf-da5e-4834-829c-175622907972

**Comment by Vinyzu** [comment] 2024-02-10 08:57
Its probably because hcaptcha_challenger is not actively maintained anymore so these tasks are unsupported. No issue in botright.
